src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Phone_Number__c</fullName>
        <label>Bank Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B.A</fullName>
                    <default>true</default>
                    <label>B.A</label>
                </value>
                <value>
                    <fullName>B.Ed</fullName>
                </value>
                <value>
                    <fullName>B.Sc</fullName>
                </value>
                <value>
                    <fullName>B.Tech</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BCA</fullName>
                </value>
                <value>
                    <fullName>M.A</fullName>
                </value>
                <value>
                    <fullName>M.Ed</fullName>
                </value>
                <value>
                    <fullName>M.Sc</fullName>
                </value>
                <value>
                    <fullName>M.Tech</fullName>
                </value>
                <value>
                    <fullName>MBA</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>Ph.D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st Year</fullName>
                    <default>true</default>
                    <label>1st Year</label>
                </value>
                <value>
                    <fullName>2nd Year</fullName>
                </value>
                <value>
                    <fullName>3rd Year</fullName>
                </value>
                <value>
                    <fullName>4th Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Donation Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exam Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_Number__c</fullName>
        <label>Father Mobile Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_s_Name__c</fullName>
        <label>Father&apos;s Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IFSC_Code__c</fullName>
        <label>IFSC Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Donation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Donation?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pending Exam Fees</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pending Fees Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Overall_Amount__c</fullName>
        <formula>Pending_Fees_Amount__c  +  Pending_Exam_Fees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pending Overall Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pin_Code__c</fullName>
        <label>Pin Code</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>15</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Art</fullName>
                    <default>true</default>
                    <label>Art</label>
                </value>
                <value>
                    <fullName>Commerce</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_ID__c</fullName>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_1st_Sem__c</fullName>
        <label>Subjects in which Back (1st Sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_2nd_Sem__c</fullName>
        <label>Subjects in which Back (2nd Sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_3rd_Sem__c</fullName>
        <label>Subjects in which Back (3rd Sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_Back_4th_Sem__c</fullName>
        <label>Subjects in which Back (4th Sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X1st_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1st Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X1st_Sem_Percentage__c</fullName>
        <label>1st Sem Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Percentage__c</fullName>
        <label>2nd Sem Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3rd_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>3rd Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X3rd_Sem_Percentage__c</fullName>
        <label>3rd Sem Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X4th_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>4th Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X4th_Sem_Percentage__c</fullName>
        <label>4th Sem Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Registrar</fullName>
        <active>true</active>
        <label>Registrar</label>
    </recordTypes>
    <recordTypes>
        <fullName>Teacher</fullName>
        <active>true</active>
        <label>Teacher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentQ.cls
public class StudentQ {
    public StudentQ() {
        Student__c student = new Student__c();
        
        //Registrar
        
        //Personal Information
        student.Date_Of_Birth__c = date.parse('5/10/2002');
        student.Name = 'Abhay Kevat';
        student.Roll_Number__c = 19026;
        student.Father_s_Name__c = 'Mohan Kevat';
        student.Father_Mobile_Number__c = '9184873834';
        student.Mobile_Number__c = '9638491657';
        student.Email__c = 'abhay.kevat@gmail.com';
        student.Home_Phone__c = '9184873834';
        student.Overall_Grade__c = 'A';
        student.Address__c = 'Vrindavan';
        student.City__c = 'Mathura';
        student.Pin_Code__c = 281003;
        student.State__c = 'Uttar Pradesh';
        string Id = [SELECT id FROM RecordType WHERE Name ='Teacher'].Id;
            
        //Class Info    
        student.Section__c = 'B';
        student.Class__c = 'B.Tech';
        student.Stream__c = 'Science';
            
        //Fees Details
        student.Current_Year__c = '1st Year';
        student.Is_Donation__c = False;
        student.Donation_Amount__c = 0;
        student.Fees_Submitted__c = True;
        student.Pending_Fees_Amount__c = 50;
        student.Exam_Fees_Submitted__c = True;
        student.Pending_Exam_Fees__c = 0;
        //student.Pending_Overall_Amount__c = ; //Not Writable
            
        //Semester Details
        student.X1st_Sem_Back__c = False;
        student.X1st_Sem_Percentage__c = 56;
        student.X2nd_Sem_Back__c = True;
        student.X2nd_Sem_Percentage__c = 60;
        student.X3rd_Sem_Back__c = False;
        student.X3rd_Sem_Percentage__c = 72;
        student.X4th_Sem_Back__c = False;
        student.X4th_Sem_Percentage__c = 69;
        student.Subjects_in_which_Back_1st_Sem__c = '';
        student.Subjects_in_which_Back_2nd_Sem__c = 'C++, DBMS';
        student.Subjects_in_which_Back_3rd_Sem__c = '';
        student.Subjects_in_which_Back_4th_Sem__c = '';
            
        //Bank Details
        student.Bank_Name__c = 'Canara Bank';
        student.IFSC_Code__c = 'CNRBOOO3424';
        student.Account_Number__c = 2147482947;
        student.Bank_Phone_Number__c = '8954199236';
            
        //insert student;
        
        List<Student__c> studentList = [SELECT Student_ID__c, Name, Roll_Number__c, Father_s_Name__c, Email__c, Mobile_Number__c FROM Student__c ORDER BY CreatedById LIMIT 5];
        for(Student__c showstudent : studentList) {
            system.debug('Check Student Data : ' + showstudent);
        }
    }   
}